package cz.octopuspro.octopusproservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-23T10:22:55.545+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://octopuspro.cz/OctopusProService", name = "IOctopusService")
@XmlSeeAlso({ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.octop_actionservice.ObjectFactory.class, cz.octopuspro.types.ObjectFactory.class, org.datacontract.schemas._2004._07.octop_actionservice_message.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface IOctopusService {

    /**
     * Načtení číselníků - Role
     */
    @WebResult(name = "ws_octop_get_LOV_RoleResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_Role", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_RoleResponse")
    @RequestWrapper(localName = "ws_octop_get_LOV_Role", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVRole")
    @WebMethod(operationName = "ws_octop_get_LOV_Role", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_Role")
    @ResponseWrapper(localName = "ws_octop_get_LOV_RoleResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVRoleResponse")
    public cz.octopuspro.types.LOVRoleResponse wsOctopGetLOVRole(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.LOVRoleRequest request
    );

    /**
     * Načtení číselníků - Země
     */
    @WebResult(name = "ws_octop_get_LOV_CountryResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_Country", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_CountryResponse")
    @RequestWrapper(localName = "ws_octop_get_LOV_Country", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVCountry")
    @WebMethod(operationName = "ws_octop_get_LOV_Country", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_Country")
    @ResponseWrapper(localName = "ws_octop_get_LOV_CountryResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVCountryResponse")
    public cz.octopuspro.types.LOVCountryResponse wsOctopGetLOVCountry(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.LOVCountryRequest request
    );

    /**
     * Metoda pro načtení jednoho záznamu monitoringu realitní inzerce
     */
    @WebResult(name = "get_tHitResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/get_tHit", output = "http://octopuspro.cz/OctopusProService/IOctopusService/get_tHitResponse")
    @RequestWrapper(localName = "get_tHit", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.GetTHit")
    @WebMethod(operationName = "get_tHit", action = "http://octopuspro.cz/OctopusProService/IOctopusService/get_tHit")
    @ResponseWrapper(localName = "get_tHitResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.GetTHitResponse")
    public cz.octopuspro.types.THitResponse getTHit(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.THitRequest request
    );

    /**
     * Metoda pro odebrání nemovitosti z hlídače nemovitostí
     */
    @WebResult(name = "ws_remove_KN_property_from_lvkeeperResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_remove_KN_property_from_lvkeeper", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_remove_KN_property_from_lvkeeperResponse")
    @RequestWrapper(localName = "ws_remove_KN_property_from_lvkeeper", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsRemoveKNPropertyFromLvkeeper")
    @WebMethod(operationName = "ws_remove_KN_property_from_lvkeeper", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_remove_KN_property_from_lvkeeper")
    @ResponseWrapper(localName = "ws_remove_KN_property_from_lvkeeperResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsRemoveKNPropertyFromLvkeeperResponse")
    public cz.octopuspro.types.WsRemoveKNPropertyFromLvkeeperResponse wsRemoveKNPropertyFromLvkeeper(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.WsRemoveKNPropertyFromLvkeeperRequest request
    );

    /**
     * Metoda pro získání rozdílového XML pro Hlídač nemovitostí
     */
    @WebResult(name = "ws_get_lvkeeper_diff_xmlResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_get_lvkeeper_diff_xml", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_get_lvkeeper_diff_xmlResponse")
    @RequestWrapper(localName = "ws_get_lvkeeper_diff_xml", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsGetLvkeeperDiffXml")
    @WebMethod(operationName = "ws_get_lvkeeper_diff_xml", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_get_lvkeeper_diff_xml")
    @ResponseWrapper(localName = "ws_get_lvkeeper_diff_xmlResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsGetLvkeeperDiffXmlResponse")
    public cz.octopuspro.types.WsGetLvkeeperDiffXmlResponse wsGetLvkeeperDiffXml(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.WsGetLvkeeperDiffXmlRequest request
    );

    /**
     * Služba pro získávání záznamů monitoringu realitní inzerce.
     */
    @WebResult(name = "ws_octop_1aResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_1a", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_1aResponse")
    @RequestWrapper(localName = "ws_octop_1a", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctop1A")
    @WebMethod(operationName = "ws_octop_1a", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_1a")
    @ResponseWrapper(localName = "ws_octop_1aResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctop1AResponse")
    public cz.octopuspro.types.THitResponse wsOctop1A(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.WsOctop1ARequest request
    );

    /**
     * Metoda pro změnu poznámky hlídané nemovitosti
     */
    @WebResult(name = "ws_change_lvkeeper_noteResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_change_lvkeeper_note", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_change_lvkeeper_noteResponse")
    @RequestWrapper(localName = "ws_change_lvkeeper_note", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsChangeLvkeeperNote")
    @WebMethod(operationName = "ws_change_lvkeeper_note", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_change_lvkeeper_note")
    @ResponseWrapper(localName = "ws_change_lvkeeper_noteResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsChangeLvkeeperNoteResponse")
    public cz.octopuspro.types.WsChangeLvkeeperNoteResponse wsChangeLvkeeperNote(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.WsChangeLvkeeperNoteRequest request
    );

    /**
     * Načtení číselníků - Region
     */
    @WebResult(name = "ws_octop_get_LOV_RegionResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_Region", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_RegionResponse")
    @RequestWrapper(localName = "ws_octop_get_LOV_Region", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVRegion")
    @WebMethod(operationName = "ws_octop_get_LOV_Region", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_Region")
    @ResponseWrapper(localName = "ws_octop_get_LOV_RegionResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVRegionResponse")
    public cz.octopuspro.types.LOVRegionResponse wsOctopGetLOVRegion(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.LOVRegionRequest request
    );

    /**
     * Služba pro načtení seznamu uživatelů, na které jsou přidělená přístupová práva
     */
    @WebResult(name = "ws_octop_get_AvailableUsersResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_AvailableUsers", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_AvailableUsersResponse")
    @RequestWrapper(localName = "ws_octop_get_AvailableUsers", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetAvailableUsers")
    @WebMethod(operationName = "ws_octop_get_AvailableUsers", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_AvailableUsers")
    @ResponseWrapper(localName = "ws_octop_get_AvailableUsersResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetAvailableUsersResponse")
    public org.datacontract.schemas._2004._07.octop_actionservice.TUserResponse wsOctopGetAvailableUsers(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.RequestBase request
    );

    /**
     * Metoda pro přidání nemovitosti do hlídače nemovitostí
     */
    @WebResult(name = "ws_add_KN_property_to_lvkeeperResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_add_KN_property_to_lvkeeper", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_add_KN_property_to_lvkeeperResponse")
    @RequestWrapper(localName = "ws_add_KN_property_to_lvkeeper", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsAddKNPropertyToLvkeeper")
    @WebMethod(operationName = "ws_add_KN_property_to_lvkeeper", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_add_KN_property_to_lvkeeper")
    @ResponseWrapper(localName = "ws_add_KN_property_to_lvkeeperResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsAddKNPropertyToLvkeeperResponse")
    public org.datacontract.schemas._2004._07.octop_actionservice_message.WsAddKNPropertyToLvkeeperResponse wsAddKNPropertyToLvkeeper(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.WsAddKNPropertyToLvkeeperRequest request
    );

    /**
     * Načtení číselníků - SubRegion
     */
    @WebResult(name = "ws_octop_get_LOV_SubRegionResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_SubRegion", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_SubRegionResponse")
    @RequestWrapper(localName = "ws_octop_get_LOV_SubRegion", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVSubRegion")
    @WebMethod(operationName = "ws_octop_get_LOV_SubRegion", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_SubRegion")
    @ResponseWrapper(localName = "ws_octop_get_LOV_SubRegionResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVSubRegionResponse")
    public cz.octopuspro.types.LOVSubRegionReponse wsOctopGetLOVSubRegion(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.LOVSubRegionRequest request
    );

    /**
     * Načtení číselníků - subkategorie
     */
    @WebResult(name = "ws_octop_get_LOV_SubCategoryResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_SubCategory", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_SubCategoryResponse")
    @RequestWrapper(localName = "ws_octop_get_LOV_SubCategory", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVSubCategory")
    @WebMethod(operationName = "ws_octop_get_LOV_SubCategory", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_SubCategory")
    @ResponseWrapper(localName = "ws_octop_get_LOV_SubCategoryResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVSubCategoryResponse")
    public cz.octopuspro.types.LOVSubCategoryResponse wsOctopGetLOVSubCategory(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.LOVSubCategoryRequest request
    );

    /**
     * Načtení číselníků - Vlastnictvi
     */
    @WebResult(name = "ws_octop_get_LOV_OwnershipResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_Ownership", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_OwnershipResponse")
    @RequestWrapper(localName = "ws_octop_get_LOV_Ownership", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVOwnership")
    @WebMethod(operationName = "ws_octop_get_LOV_Ownership", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_Ownership")
    @ResponseWrapper(localName = "ws_octop_get_LOV_OwnershipResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVOwnershipResponse")
    public cz.octopuspro.types.LOVOwnershipResponse wsOctopGetLOVOwnership(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.LOVOwnershipRequest request
    );

    /**
     * Služba pro párování inzerátu podle daných pravidel s využitím PairingAttributes
     */
    @WebResult(name = "ws_octop_pairingResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_pairing", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_pairingResponse")
    @RequestWrapper(localName = "ws_octop_pairing", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopPairing")
    @WebMethod(operationName = "ws_octop_pairing", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_pairing")
    @ResponseWrapper(localName = "ws_octop_pairingResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopPairingResponse")
    public cz.octopuspro.types.THitResponse wsOctopPairing(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.WsPairingRequest request
    );

    /**
     * Služba pro načtení seznamu vyhledávacích profilů pro daného uživatele, na kterého jsou přidělená přístupová práva
     */
    @WebResult(name = "ws_octop_get_SearchProfiles_For_UserResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_SearchProfiles_For_User", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_SearchProfiles_For_UserResponse")
    @RequestWrapper(localName = "ws_octop_get_SearchProfiles_For_User", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetSearchProfilesForUser")
    @WebMethod(operationName = "ws_octop_get_SearchProfiles_For_User", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_SearchProfiles_For_User")
    @ResponseWrapper(localName = "ws_octop_get_SearchProfiles_For_UserResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetSearchProfilesForUserResponse")
    public cz.octopuspro.types.TSearchProfileResponse wsOctopGetSearchProfilesForUser(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.TSearchProfileRequest request
    );

    /**
     * Služba pro otestování připojení pomocí přihlašovacích údajů
     */
    @WebResult(name = "ws_tryLoginResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_tryLogin", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_tryLoginResponse")
    @RequestWrapper(localName = "ws_tryLogin", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsTryLogin")
    @WebMethod(operationName = "ws_tryLogin", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_tryLogin")
    @ResponseWrapper(localName = "ws_tryLoginResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsTryLoginResponse")
    public cz.octopuspro.types.ResponseBase wsTryLogin(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.WsTryLoginRequest request
    );

    /**
     * Načtení číselníků - CommercialMode
     */
    @WebResult(name = "ws_octop_get_LOV_CommercialModeResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_CommercialMode", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_CommercialModeResponse")
    @RequestWrapper(localName = "ws_octop_get_LOV_CommercialMode", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVCommercialMode")
    @WebMethod(operationName = "ws_octop_get_LOV_CommercialMode", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_CommercialMode")
    @ResponseWrapper(localName = "ws_octop_get_LOV_CommercialModeResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVCommercialModeResponse")
    public cz.octopuspro.types.LOVCommercialModeResponse wsOctopGetLOVCommercialMode(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.LOVCommercialModeRequest request
    );

    /**
     * Načtení číselníků - Category
     */
    @WebResult(name = "ws_octop_get_LOV_CategoryResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_Category", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_CategoryResponse")
    @RequestWrapper(localName = "ws_octop_get_LOV_Category", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVCategory")
    @WebMethod(operationName = "ws_octop_get_LOV_Category", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_Category")
    @ResponseWrapper(localName = "ws_octop_get_LOV_CategoryResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVCategoryResponse")
    public cz.octopuspro.types.LOVCategoryResponse wsOctopGetLOVCategory(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.LOVCategoryRequest request
    );

    /**
     * Služba pro získávání záznamů monitoringu realitní inzerce. Vrátí všechny nové inzeráty pro daný vyhledávací profil, které ještě nebyly vyžádány.
     */
    @WebResult(name = "ws_octop_1bResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_1b", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_1bResponse")
    @RequestWrapper(localName = "ws_octop_1b", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctop1B")
    @WebMethod(operationName = "ws_octop_1b", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_1b")
    @ResponseWrapper(localName = "ws_octop_1bResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctop1BResponse")
    public cz.octopuspro.types.THitResponse wsOctop1B(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.WsOctop1BRequest request
    );

    /**
     * Test method returns 'Hello World!'
     */
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/HelloWorld", output = "http://octopuspro.cz/OctopusProService/IOctopusService/HelloWorldResponse")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://octopuspro.cz/OctopusProService/IOctopusService/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.HelloWorldResponse")
    public java.lang.String helloWorld();

    /**
     * Načtení číselníků - OfferType
     */
    @WebResult(name = "ws_octop_get_LOV_OfferTypeResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_OfferType", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_OfferTypeResponse")
    @RequestWrapper(localName = "ws_octop_get_LOV_OfferType", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVOfferType")
    @WebMethod(operationName = "ws_octop_get_LOV_OfferType", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_octop_get_LOV_OfferType")
    @ResponseWrapper(localName = "ws_octop_get_LOV_OfferTypeResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsOctopGetLOVOfferTypeResponse")
    public cz.octopuspro.types.LOVOfferTypeResponse wsOctopGetLOVOfferType(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.LOVOfferTypeRequest request
    );

    /**
     * Metoda pro nalezení nemovitosti v KN podle zadaných parametrů
     */
    @WebResult(name = "ws_find_KN_propertyResult", targetNamespace = "http://octopuspro.cz/OctopusProService")
    @Action(input = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_find_KN_property", output = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_find_KN_propertyResponse")
    @RequestWrapper(localName = "ws_find_KN_property", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsFindKNProperty")
    @WebMethod(operationName = "ws_find_KN_property", action = "http://octopuspro.cz/OctopusProService/IOctopusService/ws_find_KN_property")
    @ResponseWrapper(localName = "ws_find_KN_propertyResponse", targetNamespace = "http://octopuspro.cz/OctopusProService", className = "cz.octopuspro.octopusproservice.WsFindKNPropertyResponse")
    public cz.octopuspro.types.WsFindKNPropertyResponse wsFindKNProperty(
        @WebParam(name = "request", targetNamespace = "http://octopuspro.cz/OctopusProService")
        cz.octopuspro.types.WsFindKNPropertyByLVRequest request
    );
}
