package cz.octopuspro.octopusproservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-23T10:22:55.574+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "OctopusProService", 
                  wsdlLocation = "file:/Volumes/kfsCard/src/real/KfsOctopusWs/src/main/resources/wsdl/OctopusProService.svc.wsdl_wsdl0.wsdl",
                  targetNamespace = "http://octopuspro.cz/OctopusProService") 
public class OctopusProService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://octopuspro.cz/OctopusProService", "OctopusProService");
    public final static QName BasicHttpEndpoint = new QName("http://octopuspro.cz/OctopusProService", "basicHttpEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/Volumes/kfsCard/src/real/KfsOctopusWs/src/main/resources/wsdl/OctopusProService.svc.wsdl_wsdl0.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OctopusProService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Volumes/kfsCard/src/real/KfsOctopusWs/src/main/resources/wsdl/OctopusProService.svc.wsdl_wsdl0.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OctopusProService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OctopusProService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OctopusProService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OctopusProService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OctopusProService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OctopusProService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IOctopusService
     */
    @WebEndpoint(name = "basicHttpEndpoint")
    public IOctopusService getBasicHttpEndpoint() {
        return super.getPort(BasicHttpEndpoint, IOctopusService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOctopusService
     */
    @WebEndpoint(name = "basicHttpEndpoint")
    public IOctopusService getBasicHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(BasicHttpEndpoint, IOctopusService.class, features);
    }

}
